name: bh_demo
channels:
- conda-forge
- defaults
dependencies:
- ca-certificates
- certifi=2016.2.28=py27_1
- decorator=4.0.10=py27_0
- funcsigs=1.0.2=py27_0
- future=0.15.2=py27_0
- h5py=2.6.0=np111py27_4
- hdf5=1.8.17=2
- html5lib=0.999999999=py27_0
- icu=56.1=4
- isodate=0.5.4=py27_0
- keepalive=0.5=py27_0
- libiconv=1.14=3
- libxml2=2.9.3=9
- ncurses=5.9=10
- networkx=1.11=py27_0
- nibabel=2.0.2=py27_0
- nipype=0.12.0=py27_1
- nose=1.3.7=py27_1
- openssl=1.0.2h=2
- pandas=0.18.1=np111py27_1
- pip=8.1.2=py27_0
- prov=1.5.0=py27_0
- psutil=4.3.0=py27_0
- pydicom=0.9.9=py27_0
- pydotplus=2.0.2=py27_0
- python=2.7.12=1
- python-dateutil=2.5.3=py27_0
- pytz=2016.6.1=py27_0
- rdflib=4.2.1=py27_0
- requests=2.10.0=py27_0
- setuptools=23.0.0=py27_1
- six=1.10.0=py27_0
- sparqlwrapper=1.7.6=py27_0
- sqlite=3.13.0=1
- traits=4.5.0=py27_0
- webencodings=0.5=py27_0
- wheel=0.29.0=py27_0
- xvfbwrapper=0.2.8=py27_0
- xz=5.2.2=0
- zlib=1.2.8=3
- libgfortran=3.0.0=1
- libxslt=1.1.28=0
- lxml=3.6.1=py27_0
- mkl=11.3.3=0
- numpy=1.11.1=py27_0
- pyparsing=2.1.4=py27_0
- readline=6.2=2
- scipy=0.18.0=np111py27_0
- simplejson=3.8.2=py27_0
- tk=8.5.18=0
prefix: /opt/repronim/simple_workflow/miniconda/envs/bh_demo

